### ISSUE TITLE
수집 데이터 객체에 timeline_items 추가해 주세요

### ISSUE THREAD

**Issue by FoO-511** [DF-ATT-CK/DF_CAT_Forensic_Tool#1]
## 모든 객체에 timeline_items 추가
```
{
  ...data,
  timeline_items: [
     {
        start_time: Date,
        end_time: Date,
        name: "registry_modified_time"
    },
    {
        start_time: Date,
        end_time: Date,
        name: "logon_time"
    }
  ]
}
```
(아래에 타입으로 또 적어놓았음.)
- timeline_items은 배열이며, 배열 속의 요소 하나가 타임라인 상 요소 하나로 변환된다.
- 구간이 하나인 아티팩트 수집 결과는 timeline_items: [{start_time: 시작시간, end_time: 시작시간, name: 데이터의 키}] 로 준다.
- ART0001, E0006의 경우 아티팩트 수집결과가 명확한 구간을 보여주는데, 시작 시간과 끝 시간 중 하나가 null일 경우 유효한 시간 하나로 start_time과 end_time을 통일해서 넣는다. 이때 name에 넣을만한 키값이 2개가 되는데, "connection"같은 공통 분모를 사용하거나, 애매할 경우 ""으로 비워둔다.
- 시작 시간과 끝 시간 둘 다 유효하지 않거나(null이거나) 시간을 나타내는 데이터가 하나도 없을 경우 timeline_items 배열에 객체를 넣지 않는다.(어차피 timeline에 렌더링되지 않을 것이기 때문)
- timeline_items 배열 속 요소가 여러개인 경우(ART0004 참고), 배열에 여러개의 {start_time:Date, end_time: Date, name: 데이터키}객체를 넣는다. 
- timeline_items속에 시간 데이터를 넣어다고 해서 그 상위에 있는 시간 요소를 지우지 않는다.("folder_created_time", "registry_modified_time", "logon_time" 등의 키로 구성된 요소를 보존한 채로 timeline_items에 객체를 넣을 것)

### 아티팩트 수집결과 data 부분의 타입

```typescript
type data = {
  [key: string]: string,
  timeline_items: {start_time: string, end_time: string, name: string}[]
}
```

### 한 가지 더 요청사항
- 지금 데이터 속의 시간 요소가 모두 string인데 차라리 number으로 줬으면 좋겠음. 만약 오픈소스툴에서 리턴하는 타입이 처음부터 string이면 어쩔 수 없이 프론트에서 한글 시간 파싱을 담당해야겠지만, 오픈소스툴에서도 Date 자료형으로 반환해 준다면 숫자 형태로 바꿔서 줬으면 함!
- 수정 후 어떻게 처리했는지 알려 줄 것.

**Comment by w8385** [comment]
확인했습니다

**Comment by w8385** [comment]
### 구간 있는 아티팩트
- ART0002 (name / start_time ~ end_time)
- E0006 (decription / connection_time ~ disconnection_time)

### 구간 없는 아티팩트
- ART0001 (name / open_time)
- ART0003 (name / message_delivery_time)
- ART0005 (name / execute_time)
- ART0006 (path / modified_time)
- ART0007 (name / action_time)
- ART0008 (path / accessed_time)
- ART0009 (name / modified_time)
- ART0010 (path  / modified_time)
- ART0011 (name / modified_time)
- ART0022 (name / modified_time)
- ART0030 (title / visited_time)
- ART0033 (name / deleted_time)
- ART0054 (device_name / registry_time)
- ART0060 (url / created_time)
- ART0065
  1. (folder_created_time / folder_created_time)
  2. (registry_modified_time / registry_modified_time)
  3. (logon_time / logon_time)

**Comment by w8385** [comment]
#2
