### ISSUE TITLE
timeline_items 에 예외처리 추가 필요

### ISSUE THREAD

**Issue by FoO-511** [DF-ATT-CK/DF_CAT_Forensic_Tool#7]
### [ART0005] Recent_Files
- `N / A`가 문자열인지 다른 속성인지는 모르겠음 ㅎㅎ

### [ART0010] ShimCache
- 빈 문자열

**Comment by w8385** [comment]
5293b1fc5c91b6585d44640c7f85dbf6a24b6b81

## [ART0005] Recent_Files
- "N / A" 문자열로 예외처리함
![image](https://user-images.githubusercontent.com/52066828/207240339-43ef2aa2-ca53-4731-8aca-cd3b0e79268c.png)

## [ART0010] ShimCache
- 빈 문자열 예외처리함
![image](https://user-images.githubusercontent.com/52066828/207240313-4f75c2c3-e4e3-4b8a-9258-75f85b5583bd.png)
