### ISSUE TITLE
Jumplist 다 null 인 객체 예외처리

### ISSUE THREAD

**Issue by FoO-511** [DF-ATT-CK/DF_CAT_Forensic_Tool#8]
### [ART0008] Jump_Lists
```
{
            "name": null,
            "path": null,
            "accessed_time": null,
            "timeline_items": []
        }
```

**Comment by w8385** [comment]
ddebf8d06ed968c495ebabb46ed53ac21e5c6f5c
- null 예외처리함

![image](https://user-images.githubusercontent.com/52066828/207243664-b80e3af9-7213-44a7-bae0-c102e3400348.png)
